max_epoch: 300
max_cycle: 50
max_episode: 32
max_frames: 1000000

save_freq: 1
video_freq: 10
window_size: 100

gradient_step: 40
reset_freq: 1000000000

agent:
  hidden_dim: 64
  layer_count: 3

  actor_lr: 0.001
  actor_lr_min: 0.001
  ac_scheduler_steps: 1

  critic_lr: 0.001
  critic_lr_min: 0.001
  cr_scheduler_steps: 1

  alpha_lr: 0.0

  buffer_type: "HER"
  max_len: 1000000
  alpha: 1.0

  batch_size: 512
  gamma: 0.98
  ac_update_freq: 1

  noise_std: 0.2
  noise_clamp: 0.5

  policy_noise: 0.0
  grad_clip: 10.0

  tau: 0.05
  beta: 1.0
  beta_end: 1.0

  k_future: 4
  max_eps_len: 50

g_normalize: false
obs_normalize: false
